# Generated by Django 5.1.3 on 2024-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=255, null=True)),
                ('std_pass', models.CharField(max_length=12)),
                ('std_email', models.CharField(max_length=35, null=True, unique=True)),
                ('std_joindt', models.DateField()),
                ('std_img', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
